snapface/bots/models.py
# -*- coding: utf-8 -*-
import subprocess
import sys
from snapface.bots.bot import SenderBot

from snapface.database import (
    Column,
    db,
    Model,
    relationship,
    SurrogatePK,
)


class Bot(SurrogatePK, Model):
    __tablename__ = 'bot'
    name = Column(db.String(80), nullable=False, unique=True)
    # admins

    # Friend stuff
    add = Column(db.Boolean, default=False)
    delete = Column(db.Boolean, default=False)

    # Bot actions
    story = Column(db.Boolean, default=False)
    bot_pid = Column(db.String)
    # TODO: Add more actions

    # Store incomming
    store = Column(db.Boolean,
                   default=False)  # If the bot should save all incomming snaps to file, default botname in /static
    # Account
    username = Column(db.String, nullable=False)
    password = Column(db.String, nullable=False)

    def __init__(self, **kwargs):
        super(Bot, self).__init__(**kwargs)

    def __repr__(self):
        return '<Bot({name})>'.format(name=self.name)

    def get_cmd_args(self):
        cmd_str = '-u %s -p %s -of %s' % (self.username, self.password, self.name)
        if self.store:
            cmd_str += ' --store'
        if self.add:
            cmd_str += ' --add'
        if self.delete:
            cmd_str += ' --delete'
        return cmd_str

    def start_bot(self):
        cmd_pwd = SenderBot.get_screen_cmd('snapface:%s' % self.name)
        cmd_args = self.get_cmd_args()
        cmd = cmd_pwd + ' ' + cmd_args
        p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

        # Store the bots pid
        self.bot_pid = p.pid
        db.session.add(self)
        db.session.commit()

        while True:
            out = p.stderr.read(1)
            if out == '' and p.poll() != None:
                break
            if out != '':
                sys.stdout.write(out)
                sys.stdout.flush()

    def stop_bot(self):
        p = subprocess.Popen('kill -kill %s & screen -wipe' % self.bot_pid, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


class Friend(SurrogatePK, Model):
    __tablename__ = 'friends'
    username = Column(db.String(80), unique=True, nullable=False)
    bot_id = Column('users', db.ForeignKey('bot.id'), nullable=False)
    bot = relationship('Bot', backref='friends')

    def __init__(self, **kwargs):
        db.Model.__init__(self, **kwargs)

    def __repr__(self):
        return 'Friend({name})'.format(name=self.username)

snapface/snapface/bots/models.py
# -*- coding: utf-8 -*-

from snapface.database import (
    Column,
    db,
    Model,
    ReferenceCol,
    relationship,
    SurrogatePK,
)
from snapface.dependency.snapchat_bots import SnapchatBot


class Bot(SurrogatePK, Model, SnapchatBot):
    __tablename__ = 'bot'
    name = Column(db.String(80), nullable=False)
    # Friend stuff
    add = Column(db.Boolean, default=False)
    delete = Column(db.Boolean, default=False)

    # Bot actions
    story = Column(db.Boolean, default=False)
    store = Column(db.Boolean, default=False)
    # TODO: Add more actions

    # Store incomming
    store = Column(db.Boolean,
                   default=False)  # If the bot should save all incomming snaps to file, default botname in /static
    # Account
    username = Column(db.String, nullable=False)
    password = Column(db.String, nullable=False)

    def __init__(self, name, **kwargs):
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        return '<Role({name})>'.format(name=self.name)

    '''
    Snap specific methods
    '''
    ## Event handlers
    def on_snap(self, sender, snap):
        if self.storify:
            self.post_story(snap)
        if self.store:
            snap.save(dir_name=os.path.join(PROJECT_ROOT, 'snaps'))

    def on_friend_add(self, friend):
        if self.add:
            self.add_friend(friend)

    def on_friend_delete(self, friend):
        if self.delete:
            self.delete_friend(friend)


class Friend(SurrogatePK, Model):
    __tablename__ = 'friends'
    username = Column(db.String(80), unique=True, nullable=False)
    bot_id = ReferenceCol('users', nullable=False)
    bot = relationship('Bot', backref='friends')

    def __init__(self, name, **kwargs):
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        return '<Friend({name})>'.format(name=self.username)

snapface/user/models.py
# -*- coding: utf-8 -*-
import datetime as dt

from flask.ext.login import UserMixin

from snapface.extensions import bcrypt
from snapface.database import (
    Column,
    db,
    Model,
    ReferenceCol,
    relationship,
    SurrogatePK,
)


class Role(SurrogatePK, Model):
    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = ReferenceCol('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        return '<Role({name})>'.format(name=self.name)

class User(UserMixin, SurrogatePK, Model):

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    def __repr__(self):
        return '<User({username!r})>'.format(username=self.username)

snapface/user/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User

class RegisterForm(Form):
    username = TextField('Username',
                    validators=[DataRequired(), Length(min=3, max=25)])
    email = TextField('Email',
                    validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                                validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True

snapface/app.py
# -*- coding: utf-8 -*-
'''The app module, containing the app factory function.'''
from flask import Flask, render_template
from flask.ext.admin.contrib.sqla import ModelView
import inspect
import os
import sys
from snapface import public
from snapface import user
from snapface.settings import ProdConfig
from snapface.assets import assets
from snapface.extensions import (
    bcrypt,
    cache,
    db,
    login_manager,
    migrate,
    debug_toolbar,
    admin,
)


def create_app(config_object=ProdConfig):
    '''An application factory, as explained here:
    :param config_object: The configuration object to use.
    '''

    python_path()
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    #admin.init_app(app)
    #initialize_admin()
    return None


def initialize_admin():
    from snapface.user.models import User

    admin.add_view(ModelView(User, db.session, endpoint="users"))
    from snapface.bots.models import Bot

    admin.add_view(ModelView(Bot, db.session))
    from snapface.bots.models import Friend

    admin.add_view(ModelView(Friend, db.session))
    return None


def register_blueprints(app):
    app.register_blueprint(public.views.public_controller)
    app.register_blueprint(user.views.user_controller)
    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code

    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None


# Adding the whole working tree to the pythonpath, to avoid import errors
def python_path():
    currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
    parentdir = os.path.dirname(currentdir)
    sys.path.insert(0, parentdir)

snapface/bots/snapchat_bots/__init__.py
from snap import Snap
from bot import SnapchatBot

snapface/snapface/app.py
# -*- coding: utf-8 -*-
'''The app module, containing the app factory function.'''
from flask import Flask, render_template

from snapface.settings import ProdConfig
from snapface.assets import assets
from snapface.extensions import (
    bcrypt,
    cache,
    db,
    login_manager,
    migrate,
    debug_toolbar,
)
from snapface import public, user


def create_app(config_object=ProdConfig):
    '''An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    '''
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    return None


def register_blueprints(app):
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

snapface/snapface/user/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template
from flask.ext.login import login_required

blueprint = Blueprint("user", __name__, url_prefix='/users',
                        static_folder="../static")


@blueprint.route("/")
@login_required
def members():
    return render_template("users/members.html")

snapface/user/__init__.py
'''The user module.'''

from . import views

snapface/user/views.py
# -*- coding: utf-8 -*-

import subprocess

from flask import Blueprint, render_template, flash, url_for, redirect, request
from flask.ext.login import login_required
from snapface.bots.models import Bot
# from flask_wtf import Form
from flask.ext.wtf import Form
from wtforms.ext.sqlalchemy.orm import model_form
from snapface.extensions import db


user_controller = Blueprint("user", __name__, url_prefix='/users',
                            static_folder="../static")

BotForm = model_form(Bot, base_class=Form, exclude=['friends', 'bot_pid'])


@user_controller.route("/create/", methods=['GET', 'POST'])
@login_required
def create():
    form = BotForm(request.form)
    print 'at create'
    if form:
        bot = Bot()
        form.populate_obj(bot)
        db.session.add(bot)
        db.session.commit()
        flash('Bot created!', 'info')
    else:
        flash('Something went wrong!', 'error')

    return redirect(url_for('.bots'))


@user_controller.route("/")
@login_required
def bots():
    # Crete new bot form
    bot_form = BotForm()

    # Get the running bots
    bots = subprocess.Popen('screen -ls | grep snapface', stdout=subprocess.PIPE, shell=True)
    (output, err) = bots.communicate()
    running_bots = []
    if output:
        print 'got output'
        screen_bots = output.rstrip().split('\n')
        print screen_bots
        for bots in screen_bots:
            bots_pid = bots.replace('\t', '').split('.')[0]
            running_bots.append(Bot.query.filter(Bot.bot_pid == str(int(bots_pid) - 1)).first())
    # Get all bots
    all_boots = Bot.query.all()

    disabled_bots = list(set(all_boots) - set(running_bots))

    return render_template("users/bots.html", running_bots=running_bots, disabled_bots=disabled_bots, botform=bot_form)



@user_controller.route("/delete/<name>")
@login_required
def delete(name):
    if name:
        delete_this = Bot.query.filter(Bot.username == name).first()
        if delete_this:
            db.session.delete(delete_this)
            db.session.commit()
            flash('Bot deleted', 'success')
            return redirect(url_for('user.bots'))
        else:
            flash('Error deleting the bot', 'warning')
    flash('Input error, missing name', 'warning')
    return redirect(url_for('user.bots'))


@user_controller.route("/start/<name>")
@login_required
def start(name):
    if name:
        start_this = Bot.query.filter(Bot.username == name).first()
        if start_this:
            start_this.start_bot()
        else:
            flash('Error starting bot', 'warning')
    flash('Input error, missing name', 'warning')
    return redirect(url_for('user.bots'))


@user_controller.route("/stop/<name>")
@login_required
def stop(name):
    if name:
        stop_this = Bot.query.filter(Bot.username == name).first()
        if stop_this:
            stop_this.stop_bot()
        else:
            flash('Error starting bot', 'warning')
    flash('Input error, missing name', 'warning')
    return redirect(url_for('user.bots'))

snapface/templates/users/bots.html
{% extends "layout.html" %}
{% from 'macro.html' import render_form %}
{% block content %}
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">

        <h1>Snapchat Bot Web Interface!</h1>

        <details>
            <summary><i class="fa fa-plus-circle"></i> New Bot</summary>
            {{ render_form(botform, action_url='create/', action_text='Submit', class='', btn_class='btn btn-info') }}
        </details>
    </div><!-- /.jumbotron -->

    <div class="body-content">
        {% if running_bots|length >= 1 %}
            <h1> Running Bots</h1>
            <div class="row">
                {% for bot in running_bots %}
                    <div class="col-md-12">
                        <div class="well well-sm">
                            <div class="row">
                                <div class="col-xs-2 col-md-2 text-center">
                                    <img src="http://uxrepo.com/static/icon-sets/foundation/png32/256/000000/fi-social-snapchat-256-000000.png"
                                         alt="bootsnipp"
                                         class="img-rounded img-responsive"/>
                                </div>
                                <div class="col-xs-10 col-md-10 section-box">
                                    <h2>{{ bot.name }}</h2>
                                    <small> {{ bot.bot_pid }}</small>
                                    <form action="{{ url_for('user.stop', name=bot.username) }}">
                                        <button type="submit" class="btn btn-danger">Turn Off</button>
                                    </form>
                                    <hr/>
                                </div>

                            </div>
                            <div class="row rating-desc">
                                <div class="col-md-2"></div>
                                <div class="col-md-6">
                                    <i class="fa fa-male"></i> 36 friends
                                    <span class="separator">|</span>
                                    <i class="fa fa-camera"></i> 100 snaps
                                </div>
                                <div class="col-md-4"></div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        {% if disabled_bots|length >= 1 %}
            <h1> Disabled Bots </h1>
            <div class="row">
                {% for bot in disabled_bots %}
                    <div class="col-md-12">
                        <div class="well well-sm">
                            <div class="row">
                                <div class="col-xs-2 col-md-2 text-center">
                                    <img src="http://uxrepo.com/static/icon-sets/foundation/png32/256/000000/fi-social-snapchat-256-000000.png"
                                         alt="bootsnipp"
                                         class="img-rounded img-responsive"/>
                                </div>
                                <div class="col-xs-10 col-md-10 section-box">
                                    <div class="row">
                                        <div class="col-md-10">
                                            <h2>{{ bot.name }}</h2>
                                            <small> {{ bot.bot_pid }}</small>
                                        </div>
                                        <div class="col-md-2">
                                            <br>

                                            <form action="{{ url_for('user.start', name=bot.username) }}">
                                                <button type="submit" class="btn btn-success btn-block">Turn On</button>
                                            </form>
                                            <br>

                                            <form action="{{ url_for('user.delete', name=bot.username) }}">
                                                <button type="submit" class="btn btn-danger btn-block">Delete</button>
                                            </form>
                                        </div>
                                        <div class="col-md-1">
                                        </div>
                                        <hr/>
                                    </div>
                                </div>

                            </div>
                            <div class="row rating-desc">
                                <div class="col-md-2"></div>
                                <div class="col-md-6">
                                    <i class="fa fa-male"></i> 36 friends
                                    <span class="separator">|</span>
                                    <i class="fa fa-camera"></i> 100 snaps
                                </div>
                                <div class="col-md-4"></div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            </div>
        {% endif %}
{% endblock %}

snapface/templates/users/members.html
{% extends "layout.html" %}
{% block content %}
    <h1>Welcome {{ session.username }}</h1>
    <h3>This is the members-only page.</h3>
{% endblock %}